name: Deploy to Firebase Hosting & Functions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Setup pnpm
      - name: Setup pnpm
        run: npm install -g pnpm

      # 4. Remove node_modules and yarn.lock (like your local fix)
      - name: Clean previous dependencies
        run: |
          rm -rf node_modules
          rm -f pnpm-lock.yaml

      # 5. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 6. Clean Nuxt cache
      - name: Clean Nuxt cache
        run: npx nuxt clean

      # 7. Build Nuxt app
      - name: Build Nuxt app
        run: pnpm run build -- --preset=firebase

      # 8. Deploy to Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_ECBD0 }}
          projectId: "portfolio-ecbd0"
          channelId: live
