name: Deploy to Firebase Hosting & Functions

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Setup pnpm
      - name: Setup pnpm
        run: npm install -g pnpm

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 5. Build Nuxt app
      - name: Build Nuxt app
        run: pnpm run build -- --preset=firebase

      # 6. Install Firebase CLI
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools@latest

      # 7. Setup Firebase service account
      - name: Setup Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_ECBD0 }}" > $GITHUB_WORKSPACE/firebase-key.json
        shell: bash

      # 8. Deploy to Firebase Hosting & Functions
      - name: Deploy to Firebase
        run: npx firebase-tools deploy \
              --project portfolio-ecbd0 \
              --only hosting,functions \
              --credential $GITHUB_WORKSPACE/firebase-key.json
